name: Upload Lambda Layers to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload-layers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # cambia a tu región

      # ---------- FFMPEG ----------
      - name: Download static ffmpeg binary
        run: |
          mkdir -p layers/ffmpeg/bin
          curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
          tar -xJf ffmpeg.tar.xz --strip-components=1 -C layers/ffmpeg/bin
          chmod +x layers/ffmpeg/bin/ffmpeg

      - name: Create ffmpeg.zip
        run: |
          cd layers/ffmpeg
          zip -r ../../ffmpeg.zip .
          cd ../..

      # ---------- PUPPETEER UTILS ----------
      - name: Install puppeteer-utils dependencies
        working-directory: layers/puppeteer-utils
        run: npm ci

      - name: Compile puppeteer-utils to dist
        working-directory: layers/puppeteer-utils
        run: npm run build

      - name: Create utils.zip
        run: |
          mkdir -p layer-build/nodejs
          cp -r layers/puppeteer-utils/dist/* layer-build/nodejs/
          cp -r layers/puppeteer-utils/node_modules layer-build/nodejs/
          cp layers/puppeteer-utils/package.json layer-build/nodejs/
          cd layer-build
          zip -r ../utils.zip nodejs
          cd ..

      # ---------- UPLOAD ----------
      - name: Upload ffmpeg.zip to S3
        run: aws s3 cp ffmpeg.zip s3://was-shared-lambda-layers/ffmpeg.zip

      - name: Upload utils.zip to S3
        run: aws s3 cp utils.zip s3://was-shared-lambda-layers/puppeteer-utils.zip
